services:
  db:
    build: ./db
    container_name: tienda-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  backend:
    build: ./backend
    container_name: tienda-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: tienda_perritos
      DB_PORT: "3306"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend_net
      - backend_net

  frontend:
    build: ./frontend
    container_name: tienda-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx-compose.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - frontend_net

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  dbdata:
