version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  backend-ventas:
    image: ${ECR_REGISTRY}/backend-ventas:latest
    container_name: backend_ventas
    restart: always
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=ventas
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network

  backend-despachos:
    image: ${ECR_REGISTRY}/backend-despachos:latest
    container_name: backend_despachos
    restart: always
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=despachos
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    image: ${ECR_REGISTRY}/frontend-despachos:latest
    container_name: frontend_app
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
